# Alacritty Configuration - Ocean at Night Theme

[window]
opacity = 0.85
blur = true
padding.x = 10
padding.y = 10

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 11.0

[colors.primary]
background = "#0a1628"
foreground = "#c5d9ed"

[colors.cursor]
text = "#0a1628"
cursor = "#c5d9ed"

[colors.normal]
black = "#152238"
red = "#e74c3c"
green = "#89dceb"
yellow = "#f9e2af"
blue = "#2a5f8f"
magenta = "#b4a0e5"
cyan = "#89dceb"
white = "#c5d9ed"

[colors.bright]
black = "#6b8ba8"
red = "#e74c3c"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#1e3a5f"
magenta = "#cba6f7"
cyan = "#94e2d5"
white = "#ffffff"
